version: "3.9"

services:

  webapp:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    command: [ "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - pgdb

  redis:
    image: redis
    restart: always

  worker:
    restart: always
    build:
      context: .
    command: [ "celery", "-A", "mailings_project", "worker"]

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
