# Generated by Django 5.0.1 on 2024-01-24 10:22

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='Телефон')),
                ('cod_phone', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Code must be 3 digits', regex='^[0-9]{3}$')], verbose_name='Код оператора')),
                ('tag', models.CharField(max_length=25, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_mailing', models.DateTimeField(verbose_name='Дата старта рассылки')),
                ('message_text', models.TextField(verbose_name='Текст рассылки')),
                ('filter', models.CharField(max_length=25, verbose_name='Фильтр')),
                ('end_date_time_mailing', models.DateTimeField(verbose_name='Дата окончания рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_create', models.DateTimeField(verbose_name='Дата отправки письма')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='mail.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='mailing', to='mail.mailing', verbose_name='Рассылка')),
            ],
        ),
    ]
